export const ACTION_TYPE = {
  CHATS_FETCH_SUCCESS: "CHATS_FETCH_SUCCESS",
  AUTH_REGISTER_INIT: "AUTH_REGISTER_INIT",
  AUTH_REGISTER_SUCCESS: "AUTH_REGISTER_SUCCESS",
  AUTH_ON_INIT: "AUTH_ON_INIT",
  AUTH_ON_SUCCESS: "AUTH_ON_SUCCESS",
  AUTH_ON_ERROR: "AUTH_ON_ERROR",
  AUTH_LOGOUT_SUCCESS: "AUTH_LOGOUT_SUCCESS",
  AUTH_LOGIN_INIT: "AUTH_LOGIN_INIT",
  AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS"
}