export const ACTION_TYPE = {
  CHATS_FETCH_SUCCESS: "CHATS_FETCH_SUCCESS",
  AUTH_REGISTER_SUCCESS: "AUTH_REGISTER_SUCCESS",
  AUTH_ON_INIT: "AUTH_ON_INIT",
  AUTH_ON_SUCCESS: "AUTH_ON_SUCCESS",
  AUTH_ON_ERROR: "AUTH_ON_ERROR"
}